matrix:
    include:
        - os: linux
          sudo: true
          dist: trusty
          group: edge
          install: ./setup
        - os: osx
          install:
            - sudo easy_install pip
            - sudo pip install --upgrade pip
            - ./setup
script:
  - cd ./firmware/FreeRTOS/
  - source env.sh
  - make build
  - ls ./bin/firmware.elf
  - ls ./bin/firmware.hex
  - ls ./bin/firmware.lst
  - ls ./bin/firmware.map
  - cd test/simple-test/
  - make